version: "3"

networks:
  analytics-net:

services:
  mysql:
    image: amd64/mysql:5.7
    container_name: mysql
    networks:
      analytics-net:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=hello.openhn666
      - MYSQL_DATABASE=analytics
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./docker/mysql:/var/lib/mysql
      #- ./docker/mysql/my.cnf:/etc/mysql/my.cnf # mysql配置文件
      #- ./docker/mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
  clickhouse:
    image: clickhouse/clickhouse-server:22.6.3.35
    container_name: clickhouse
    networks:
      analytics-net:
    expose:
      - 8123
      - 9009
    ports:
      - '8123:8123'
      - '9009:9009'
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_USER=root
      - CLICKHOUSE_DB=analytics
      - CLICKHOUSE_PASSWORD=hello.openhn666
    volumes:
      - ./docker/clickhouse/data:/var/lib/clickhouse
      # 按需使用
      # - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      # - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
  redis:
    container_name: redis
    image: 'redis:6.2'
    networks:
      analytics-net:
    ports:
      - '6379:6379'
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./docker/redis/data:/data:rw
    command: redis-server --requirepass hello.openhn666

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    networks:
      analytics-net:
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      analytics-net:
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./docker/kafka-logs:/kafka
    depends_on:
      - zookeeper

